const PluginDir = "/usr/lib/nagios/plugins"

const ManubulonPluginDir = "/usr/lib/nagios/plugins"

const PluginContribDir = "/usr/lib/nagios/plugins"

const NodeName = "icinga-master"

const ZoneName = "master"

const TicketSalt = "e537d2cc85c9c1c805cd3832a71481d4"
