const PluginDir = "/usr/lib/nagios/plugins"

const ManubulonPluginDir = "/usr/lib/nagios/plugins"

const PluginContribDir = "/usr/lib/nagios/plugins"

const NodeName = "icinga-master"

const ZoneName = "master"

const TicketSalt = "7d65c57877b73e0df7fccb1cc43c3ee3"
