const PluginDir = "/usr/lib/nagios/plugins"

const ManubulonPluginDir = "/usr/lib/nagios/plugins"

const PluginContribDir = "/usr/lib/nagios/plugins"

const NodeName = "icinga-master"

const ZoneName = "master"

const TicketSalt = "c7fd4c4c4a0a6983fcef32ad420606c0"
