[project]
name = "pretiac"
version = "0.7.0"
description = "pretiac: A PREtty Typed Icinga2 Api Client."
authors = [{ name = "Josef Friedrich", email = "josef@friedrich.rocks" }]
requires-python = ">=3.10,<4"
readme = "README.rst"
license = "GPL-3.0-only"
classifiers = [
    "Topic :: Utilities",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "click>=8.3.3",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "rich>=15.0.0",
    "types-pyyaml>=6.0.12.20260408",
    "types-requests>=2.33.0.20260408",
]

[project.urls]
Repository = "https://github.com/Josef-Friedrich/PREtty-Typed-Icinga2-Api-Client_py"

[project.scripts]
pretiac = "pretiac.cli:main"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "mypy>=1.19.1",
]

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[tool.ruff.format]
docstring-code-format = true
