api_endpoint_host: localhost
api_endpoint_port: 5665
http_basic_username: apiuser
http_basic_password: password
new_host_defaults:
  templates: [passive-host]
new_service_defaults:
  templates: [passive-service]
  attrs:
    check_interval: 120
