---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      - run: chmod -R 777 ./resources/etc-icinga2
      - name: Start docker container
        uses: docker://docker
        with:
          args: run --name icinga-master -v ${{ github.workspace }}/resources/etc-icinga2:/data/etc/icinga2 -h icinga-master -p 5665:5665 -e ICINGA_MASTER=1 -d icinga/icinga2

      - run: sleep 10

      - name: logs docker container
        uses: docker://docker
        with:
          args: logs icinga-master

      - run: curl -k -s -S -i -u apiuser:password 'https://localhost:5665/v1'

      - name: Install the monitoring-plugins using apt
        run: sudo apt-get install -y monitoring-plugins

      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel virtualenv tox tox-gh-actions

      # https://github.com/ymyzk/tox-gh-actions
      - name: Run tox targets for ${{ matrix.python-version }}
        run: python -m tox
